parameters:
    ckmb_config.menu.provider.class: CKMB\Bundle\ConfigKnpMenuBundle\Provider\ConfigurationMenuProvider

services:
    ckmb_config.menu.provider:
        class: '%ckmb_config.menu.provider.class%'
        arguments:
            - '@knp_menu.factory'
            - '@event_dispatcher'
            - '@security.authorization_checker'
        tags:
            - { name: knp_menu.provider }
